### ISSUE TITLE
Masken erstellen 

### ISSUE THREAD

**Issue by SticklerJaeger81** [CaptainMegane/tiny_lagerverwaltung#1]
Es müssen folgende Masken erstellt werden:
1. Stammdaten (Userverwaltung).
2. Kundenverwaltung, schon in progress, erste datei kundenstamm_new.cfm
3. Aktenvernichtung
4. Akteneinlagerung
5. Abrufe bearbeiten
6. Rückläufe bearbeiten
7. Akteninformation

URL für Testserver: xxx

**Comment by CaptainMegane** [comment]
Hier nochmal die Übersicht der zu erstellenden Masken!

**Comment by CaptainMegane** [comment]
Bereits erledigt ist: 
Kundenverwaltung (zu 90%), nur Kunden löschen fehlt.

**Comment by CaptainMegane** [comment]
Alle wichtigen Masken für Phase 1 sind erstellt
